services:
  proxy:
    build: ./proxy
    ports:
      - "8080:80"
    networks:
      - local-bridge
    depends_on:
      - sitio1 
      - sitio2
      - sitio3
  
  sitio1:
    build: ./sitio1
    networks:
      - local-bridge
    
  sitio2:
    build: ./sitio2
    networks:
      - local-bridge
  
  sitio3:
    build: ./sitio3
    networks:
      - local-bridge
  
networks:
  local-bridge:
    driver: bridge
